[package]
name = "ice"
version = "0.1.0-alpha.19"
edition = "2021"

[dependencies]
ice-server.workspace = true
ice-core = { workspace = true, features = ["clap"] }
ice-util.workspace = true
toml = "0.8.6"
serde = { version = "1.0.190", features = ["derive"] }
clap = { version = "4.4.18", features = ["derive"] }
log = "0.4"
env_logger = "0.10.1"
regex = "1.10.2"
reqwest = { version = "0.11.22", features = ["blocking", "json", "stream"] }
serde_json = "1.0.120"
chrono = "0.4.38"
tracing = "0.1.40"
sha = "1.0.3"
color-print = "0.3.6"
tracing-subscriber = "0.3.18"
toml_edit = { version = "0.22.16", features = ["serde"] }
tokio = { version = "1.38.1", features = ["full"] }


[workspace]
members = ["packages/*"]

[workspace.dependencies]
ice-server = { path = "packages/ice-server" }
ice-core = { path = "packages/ice-core" }
ice-util = { path = "packages/ice-util" }
