[package]
name = "ice-util"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
futures-util = "0.3.30"
regex = "1.10.5"
reqwest = { version = "0.12.5", features = ["stream"] }
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
sha = "1.0.3"
tokio = { version = "1.38.1", features = ["full"] }
