[package]
name = "ice-api-tool"
version = "0.1.0"
edition = "2021"

[dependencies]
ice-util.workspace = true
reqwest = { version = "0.12.5", features = ["blocking", "stream", "json"] }
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
tokio = { version = "1.38.1", features = ["full"] }
anyhow = "1.0.87"