[package]
name = "ice-api-tool"
version = "0.1.0"
edition = "2021"

[dependencies]
ice-util.workspace = true
reqwest = { version = "0.12.5", features = ["stream", "json"] }
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
anyhow.workspace = true

[dev-dependencies]
tokio = { version = "1.46.1", features = ["full"] }
async-compat.workspace = true
smol.workspace = true
smol-macros.workspace = true
macro_rules_attribute.workspace = true
