[package]
name = "ice-server"
version = "0.1.0"
edition = "2021"

[dependencies]
ice-util.workspace = true
ice-core.workspace = true
chrono = "0.4.38"
log = "0.4.22"
regex = "1.10.5"
serde = { version = "1.0.190", features = ["derive"] }
toml = "0.8.15"
# tokio = { version = "1.39.2", features = ["full"] }
smol = "2.0.2"
tracing = "0.1.40"
rhai = { version = "1.19.0", features = ["sync", "serde"] }
rhai-fs = { version = "0.1.2", features = ["sync"] }