[package]
name = "ice-core"
version = "0.1.0"
edition = "2021"

[dependencies]
ice-api-tool.workspace = true
ice-util.workspace = true
log = "0.4.22"
reqwest = { version = "0.12.5" }
clap = { version = "4.5.9", optional = true }
serde = { version = "1.0.217", features = ["derive"] }
smol.workspace = true
anyhow.workspace = true
async-compat.workspace = true

[features]
clap = ["dep:clap"]
